### ISSUE TITLE
Error launching the app on osx

### ISSUE THREAD

**Issue by andreacfm** [SamyPesse/tv.js#6]
After rake install and rake run.
localhost:8888 show this error:

Error: ENOENT, stat '[........]/tv.js/public/main/build/index.html'

**Comment by joaosoares** [comment]
I have the same problem, even if I try to directly `rake run` as mentioned in the readme.

**Comment by devnacho** [comment]
I have the same problem!

**Comment by AaronO** [comment]
It looks like you haven't built the client code to do so, simply run.

```
rake build
```

That will build the client.

To do everything (install external dependencies, build an run) simply do:

```
rake install && rake
```

That will do the job.

This should work for you guys. Let me know and I'll close the issue accordingly.

**Comment by joaosoares** [comment]
Thanks. I used `rake build` again, and noticed a problem during the installation of a dependency (yapp.js). To install it correctly I used the command:

```
npm install -g git://github.com/FriendCode/yapp.js.git
```

Now the server runs without any problem. However, I still couldn't get to download torrents, since the loading bar is always stuck at 0% and Chrome's javascript console indicates the absence of a `video.js.map` file. Should I create a new issue about this?

**Comment by devnacho** [comment]
Installing yapp solved the problem!

**Comment by devnacho** [comment]
It works but as Joao I can't download any torrent .. it is stuck at 0% and 0kb/s

**Comment by AaronO** [comment]
@jgnatch @joaosoares 

Some torrents may be slow, or may not work, that depends on two things, the film and the torrent picking algorithm.

I have some good improvements for the torrent picking algorithm comming see #9 .

As of now the torrent picking algorithm is dumb check out the code in lib/torrents.js, so I would not be surprised if for some films it doesn't pick the best or optimal torrent.

I'll get samy to maybe add some extra info about the torrent to the UI (number of seeders ...)

In the meantime, try with other films. (the error could also come from your router not supporting or being configured for UPnP, in which case torrents in general shouldn't work for you)

Let me know about the above, and look forward to coming improvements in the torrent ranking and picking algorithm

**Comment by andreacfm** [comment]
I still get this error:

Error: ENOENT, no such file or directory '/Users/andrea/dev/code/github/tv.js/public/remote/ressources/images'

Is possible 'ressources' is a typo?

Andrea

On Jul 8, 2013, at 11:10 PM, AaronO notifications@github.com wrote:

> @jgnatch @joaosoares
> 
> Some torrents may be slow, or may not work, that depends on two things, the film and the torrent picking algorithm.
> 
> I have some good improvements for the torrent picking algorithm comming see #9 .
> 
> As of now the torrent picking algorithm is dumb check out the code in lib/torrents.js, so I would not be surprised if for some films it doesn't pick the best or optimal torrent.
> 
> I'll get samy to maybe add some extra info about the torrent to the UI (number of seeders ...)
> 
> In the meantime, try with other films. (the error could also come from your router not supporting or being configured for UPnP, in which case torrents in general shouldn't work for you)
> 
> Let me know about the above, and look forward to coming improvements in the torrent ranking and picking algorithm
> 
> —
> Reply to this email directly or view it on GitHub.

Andrea Campolonghi
acampolonghi@gmail.com

**Comment by AaronO** [comment]
@andreacfm That error is non critical. It's caused simply since the public/remote/ressources/images/ folder is empty and thus, git does not push it to the tree.

"ressources" is indeed a typo, it's french for "resources" actually (Samy must have made the mistake because he's french.

The ENOENT error is called due to this line https://github.com/SamyPesse/tv.js/blob/master/public/remote/build.js#L25, which is telling the yapp,js build system to copy the ressources/images folder over to the the static files.

So it's an easy fix, and a non critical error.
